### ISSUE TITLE
SLF4j 2.0.x Support with Log4j2

### ISSUE THREAD

**Issue by desilvai-target** [mockk/mockk#989]
### Summary
From #243, mockk checks if SLF4j is available for use as a logger by checking the classpath for `org.slf4j.impl.StaticLoggerBinder`.  However, as of SLF4j 2.x, this file doesn't exist in the SLF4j implementations (we checked logback and the `log4j-slf4j2-impl` implementations).  This can lead to the incorrect logger being used, or, if the wrong connector is on the classpath, an exception being thrown.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior
SLF4j 2.x loggers are used by mockk if present in classpath.

### Current Behavior
mockk cannot locate the SLF4j 2.x logger.  This disables logging within our tests.  

When we include packages with transitive dependencies on an older SLF4j implementation, this causes a `NoSuchMethodError` during mock initialization. 

### Solution
The line at issue is in `io.mockk.impl.log.JvmLogging::slf4jOrJulLogging()`.  Rather than checking for files in the classpath, we can attempt to create an SLF4j logger for any class and if it fails, fall back to the JULLogger.  This will allow mockk to work with both SLF4j 1.7.x and 2.x and be resistant to future SLF4j changes.

**Comment by Raibaz** [comment]
Sorry for the delay, v1.13.4 is out now.

**Comment by Slava-Miligoulo-Target** [comment]
Awesome, wrapped updating things on our and it's working great.  Thanks!

**Comment by desilvai-target** [comment]
As Slava said, it is working great on our end.  Thank you both!  Really appreciate both of your work on this!

**Comment by jhackel-hypo** [comment]
This seems to break tests in Spring Boot 2.x applications. Since we updated to version 1.13.4 of mockk, nothing is logged anymore for out tests. Instead we get this error:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/jh/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.11/4741689214e9d1e8408b206506cbe76d1c6a7d60/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

**Comment by desilvai-target** [comment]
If you update to the latest version of your SLF4J bindings for logback, it should work just fine.  SLF4J 1.7.x and lower are out of active development (https://www.slf4j.org/download.html).  This change pushes up to SLF4J 2.0.x, which is under active development (and get security updates).

**Comment by desilvai-target** [comment]
My coworker submitted a PR to downgrade the SLF4J version in Mockk because it isn't essential to the fix (#1046).  In the interim, you exclude the SLF4J version coming in from Mockk.
