### ISSUE TITLE
ofType() matcher no longer works on kotlin 1.4.20 and mockk 1.10.4 for Function including generics

### ISSUE THREAD

**Issue by joaodias14** [mockk/mockk#555]
### Prerequisites
Please answer the following questions for yourself before submitting an issue.
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior
It should be able to match Function including generics as it did in kotlin 1.3.70 and mockk 1.10.0.

### Current Behavior
Compilation error: "Cannot use 'Nothing' as reified type parameter".

#### Steps to Reproduce
Using the code in the example project below, do the following:
1. Run tests in FunctionMatcherClientServiceTest and check that they pass;
2. In pom.xml comment lines 17 and 26 and uncomment lines 18 an 27;
3. Rebuild the project and check that it does not build anymore.

#### Context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.4
* OS: MacOS
* Kotlin version: 1.4.20
* JDK version: 11
* JUnit version: 5.7
* Type of test: unit test

#### Minimal reproducible code (the gist of this issue)
Code available in https://github.com/joaodias14/mockk-function-matcher-example.

**Comment by joaodias14** [comment]
It turns out that the "root cause" is the change from kotlin 1.3.70 to kotlin 1.4.20. Do you have any idea why this is happening?

**Comment by Raibaz** [comment]
This is likely due to a change in reified type handling introduced in Kotlin 1.4.

However, I think you can still have your tests work properly if you use `any()` rather than `ofType()` for the cases when you are not specifying any type.

Does this make sense?

**Comment by joaodias14** [comment]
Hi @Raibaz, thanks for the quick feedback, but `any()` renders the same compilation error.

**Comment by joaodias14** [comment]
Hi @Raibaz, any further feedback about this? This is preventing us to upgrade kotlin version. Thanks.

**Comment by Raibaz** [comment]
Hi @joaodias14, we just released v1.10.5 that reverts back to Kotlin 1.3.72, can you please try upgrading Mockk and see if it solves your issue?

**Comment by joaodias14** [comment]
Hi @Raibaz, thanks for your feedback.
It does work if we keep using Kotlin 1.3.72, but it still prevents us from upgrading to Kotlin 1.4.20. If we do so, the compilation error kicks in again. So I wouldn't say this is the solution.

**Comment by Raibaz** [comment]
This should be fixed by v1.11.0

**Comment by joaodias14** [comment]
Many thanks @Raibaz !

**Comment by joaodias14** [comment]
@Raibaz can you please add the important label so that the ticket is not closed?
Additionally, any idea when this will be fixed? Thanks!
