### ISSUE TITLE
noclassdeffounderror: io/mockk/valueclasssupportkt in maven build

### ISSUE THREAD

**Issue by pas2al** [mockk/mockk#952]
Maven builds erros with:
`noclassdeffounderror: io/mockk/valueclasssupportkt`

- Version 1.13.2 is used (`mockk-jvm`)

**Comment by pas2al** [comment]
Does anyone have an idea what the problem might be? It fails after updating from 1.12.5 to a newer version (1.13.x). Even the most simple tests fail. Just using simple `@Mockk`, `@InjectMockk`, and some simple mocking via `every { ... } returns Unit`

**Comment by cheister** [comment]
I got this error when I only had `io.mockk:mockk` as a dependency.  Adding an additional dependency on `io.mockk:mockk-jvm` worked for me.
