### ISSUE TITLE
mockk-1.12.6.jar from MavenCentral is empty

### ISSUE THREAD

**Issue by stefanzilske** [mockk/mockk#884]
> Just be aware about usual MockK support pattern. 
> Tickets are checked from time to time, replied, discussed, labeled, e.t.c.
> But real fixes are applied in a month-two month period in a bunch.
> If you think this is unacceptable, go on, join the project, change the world.

## Please remove sections wisely

Below information is actually needed to make all the process of fixing faster.
Choose main points. Don't blindly follow this as a set of rules. 
Don't waste much time. Usually, the main thing is to have a good reproducible minimal code.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed 

### Expected Behavior

Upgrading to mock 1.12.6 should contain no breaking changes.

### Current Behavior

The jar downloaded from Maven Central is empty, it contains only META-INF directory: https://search.maven.org/artifact/io.mockk/mockk/1.12.6/jar

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.6
* OS: macOS 12.5.1
* Kotlin version: 1.7.10
* JDK version: 17.0.4
* JUnit version: 5.8.2
* Type of test: any test

**Comment by sschuberth** [comment]
Also e.g. https://repo.maven.apache.org/maven2/io/mockk/mockk-jvm/1.12.6/mockk-jvm-1.12.6.pom is missing completely.

**Comment by qoomon** [comment]
An other strange thing is that https://repo.maven.apache.org/maven2/io/mockk/mockk-jvm/1.12.6/ does exist, however https://repo.maven.apache.org/maven2/io/mockk/mockk-jvm/1.12.5/ does not

**Comment by Raibaz** [comment]
Definitely something wrong with the new buildfiles introduced lately, my bad, going to fix this.

Sorry for the inconvenience.

**Comment by Raibaz** [comment]
So, apparently switching to the multiplatform build introduced the `mockk-jvm` module that is, in fact, new, as @qoomon noticed.

It's being published on sonatype, but then it does not go to maven central.

Looking into it, it should just be a matter of telling sonatype to publish all modules to maven central.

**Comment by aSemy** [comment]
> An other strange thing is that https://repo.maven.apache.org/maven2/io/mockk/mockk-jvm/1.12.6/ does exist, however https://repo.maven.apache.org/maven2/io/mockk/mockk-jvm/1.12.5/ does not

Previously the `mockk-jvm` project was named `mockk`

https://github.com/mockk/mockk/blob/1d1e6a8802e4db71cecc3142cac3a0cb0e7f1ae2/mockk/jvm/build.gradle.kts#L41-L43

Now the naming is handled by the Kotlin Multiplatform project, which publishes a common `mockk` library, and a JVM variant.

**Comment by Raibaz** [comment]
Yep I figured so, so now the `io.mockk:mockk` dependency is just a container that includes the JVM variant as a transitive dependency.

It shouldn't be an issue, if only mockk-jvm was published on maven central :)

**Comment by Raibaz** [comment]
Added a comment here https://issues.sonatype.org/browse/OSSRH-35388 to see if it's an issue with sonatype.

**Comment by alexroussiereTT** [comment]
Idk if this is related, but was the `mockk-android` library supposed to get the `1.12.6` version as well? From https://search.maven.org/search?q=g:io.mockk it seemed that there are 4 artifacts that didn't get the update yet, but maybe it's because the release was not long ago? 
Just an observation :)

**Comment by Raibaz** [comment]
Ok i got to publish `1.12.7` to maven central, which seemingly includes `mockk-jvm` as well.

I'd like some of you to at least give it a try before publishing a release on GitHub, can you please try upgrading to `1.12.7` and checking if everything is fine?

Tagging folks like @qoomon and @aSemy in case they can provide feedback

**Comment by alvr** [comment]
1.12.7 is working fine for me @Raibaz

**Comment by goerge** [comment]
@Raibaz LGTM, too!

**Comment by SimonMarquis** [comment]
It looks good for the mockk-android artifact as well

```
io.mockk:mockk-android:1.12.7
├─ io.mockk:mockk-agent-android:1.12.7 (runtime)
│  ├─ com.linkedin.dexmaker:dexmaker:2.28.1 (runtime)
│  │  └─ com.jakewharton.android.repackaged:dalvik-dx:9.0.0_r3 (runtime)
│  │     └─ junit:junit:4.12 (test)
│  │        └─ org.hamcrest:hamcrest-core:1.3
│  ├─ io.mockk:mockk-agent-api:1.12.7 (compile)
│  │  └─ org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10 (runtime)
│  │     ├─ org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10 (compile)
│  │     │  └─ org.jetbrains.kotlin:kotlin-stdlib:1.7.10 (compile)
│  │     │     ├─ org.jetbrains.kotlin:kotlin-stdlib-common:1.7.10 (compile)
│  │     │     └─ org.jetbrains:annotations:13.0 (compile)
│  │     └─ org.jetbrains.kotlin:kotlin-stdlib:1.7.10 (compile)️
│  ├─ io.mockk:mockk-agent:1.12.7 (compile)
│  │  ├─ io.mockk:mockk-agent-api:1.12.7 (runtime)
│  │  │  └─ org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10 (runtime)️
│  │  └─ org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10 (runtime)️
│  ├─ org.jetbrains.kotlin:kotlin-reflect:1.7.10 (runtime)
│  │  └─ org.jetbrains.kotlin:kotlin-stdlib:1.7.10 (compile)️
│  ├─ org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10 (compile)
│  │  ├─ org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10 (compile)️
│  │  └─ org.jetbrains.kotlin:kotlin-stdlib:1.7.10 (compile)️
│  └─ org.objenesis:objenesis:3.2 (runtime)
│     └─ org.objenesis:objenesis-test: (test)
├─ io.mockk:mockk-agent-api:1.12.7 (runtime)️
├─ io.mockk:mockk:1.12.7 (runtime)
│  ├─ io.mockk:mockk-dsl:1.12.7 (runtime)
│  │  └─ org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10 (runtime)️
│  └─ org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10 (runtime)️
├─ org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10 (compile)️
└─ org.jetbrains.kotlinx:kotlinx-coroutines-core: (runtime)
```

**Comment by alexroussiereTT** [comment]
`mockk-android` is working for me as well 💯

**Comment by Raibaz** [comment]
Ok, I released 1.12.7, thanks a lot everyone for the feedback and the patience!

**Comment by stefanzilske** [comment]
To me it's still not resolved. mockk-1.12.7.jar is still empty. Do I have to switch to mockk-jvm dependency instead?

cf. #891

**Comment by sschuberth** [comment]
> To me it's still not resolved. mockk-1.12.7.jar is still empty. Do I have to switch to mockk-jvm dependency instead?

At least Gradle picks the JVM artifact automatically, and I also can confirm our project to build fine with MockK 1.12.7.

**Comment by aSemy** [comment]
If you're using Maven, can you try changing `mockk` to `mockk-jvm`?

```xml
<dependency>
  <groupId>io.mockk</groupId>
  <!-- <artifactId>mockk</artifactId> -->
  <artifactId>mockk-jvm</artifactId>
  <version>${mockk.version}</version>
 </dependency>
```

**Comment by stefanzilske** [comment]
@aSemy yes code compiles again when I switch to mockk-jvm. However during test execution I am now getting the following exceptions:

```
java.lang.NoSuchMethodError: 'kotlin.reflect.KClass io.mockk.ValueClassSupportKt.boxedClass(kotlin.reflect.KClass)'

	at io.mockk.impl.instantiation.JvmMockFactoryHelper.toDescription$mockk(JvmMockFactoryHelper.kt:150)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	at io.mockk.proxy.jvm.advice.BaseAdvice.handle(BaseAdvice.kt:42)
	at io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.interceptNoSuper(JvmMockKProxyInterceptor.java:45)
	at ...
	at ...
	at ...
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:25)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:78)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:40)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:98)
```

Is this a separate issue?

**Comment by Michael-Duivestein** [comment]
@stefanzilske I'm seeing something similar after trying to upgrade from `mockk` 1.12.4 to `mockk-jvm` 1.12.7.
Using Maven.
```
java.lang.NoSuchMethodError: 'void io.mockk.MethodDescription.<init>(java.lang.String, kotlin.reflect.KClass, boolean, boolean, boolean, kotlin.reflect.KClass, java.util.List, int, boolean)'

	at io.mockk.impl.instantiation.JvmMockFactoryHelper.toDescription$mockk(JvmMockFactoryHelper.kt:136)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:27)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	...
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:104)
```

**Comment by aSemy** [comment]
`ValueClassSupportKt` suggests to me it's this issue: https://github.com/mockk/mockk/issues/868#issuecomment-1224764393
