### PR TITLE
Enable clearAllMocks to clear only thread-local mocks.

### PR DESCRIPTION
**Pull request by xzhang-brex**
Hey guys,

Currently, `clearAllMocks` clears all mocks regardless of the thread where the mock was created, which complicates running tests in parallel. Many issues and discussions about this have been posted, and they can be found at https://github.com/mockk/mockk/issues/301, https://github.com/mockk/mockk/issues/1062, https://github.com/mockk/mockk/issues/764, https://github.com/mockk/mockk/issues/860.

This PR demonstrates a way to allow clearAllMocks to clear only thread-local mocks. I haven't added unit tests yet because I need to know first if this approach is acceptable. If it is accepted, I will add all necessary changes related to this PR, including unit tests and documentation. I'll also try to add the same thread-safety support to other methods like `mockkStatic`.

Looking forward to your feedback. Thank you!

### CODE REVIEW

**Comment by xzhang-brex** [comment]
@oleksiyp @Raibaz hey guys, would you mind to take a look? thank you!

**Comment by Raibaz** [comment]
Can you please run `./gradlew :mockk-dsl:apiDump` to update the api definition files?

**Comment by xzhang-brex** [comment]
@Raibaz Updated api definition files and pls let me know if this approach is acceptable and I will write unit tests/doc etc.

**Comment by Raibaz** [comment]
Yes I like the approach, feel free to add unit tests and docs.

Thanks!

**Comment by xzhang-brex** [comment]
@Raibaz I've added unit test and doc, pls review, thank you!

**Comment by Raibaz** [comment]
Thanks!

**Comment by jzeferino** [comment]
hey, we have a usecase for some tests were we call `clearAllMocks()` before the tests run.
after updating to 1.13.12 we got a runtime error:

`java.lang.NoSuchMethodError: 'void io.mockk.MockKGateway$Clearer.clearAll(io.mockk.MockKGateway$ClearOptions)'`

any suggestion?
