### ISSUE TITLE
"Duplicate class io.mockk.ValueClassSupportKt found" when using in 1.12.0

### ISSUE THREAD

**Issue by StormPooper** [mockk/mockk#722]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behaviour

Android instrumented tests should run.

### Current Behaviour

Android instrumented tests fail with `Duplicate class io.mockk.ValueClassSupportKt found` compilation error (see stack trace below).

### Failure Information (for bugs)

When upgrading from 1.11.0 to 1.12.0, tests no longer run. Seems to be affecting others that have commented on #653.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run tests successfully
2. Upgrade Gradle dependencies to 1.12.0
3. Tests fail

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.0
* OS: macOS 12
* Kotlin version: 1.53.1
* JDK version: 11
* JUnit version: 5
* Type of test: android instrumented test

#### Stack trace

```
> Task :app:checkDebugAndroidTestDuplicateClasses FAILED
Execution failed for task ':app:checkDebugAndroidTestDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class io.mockk.ValueClassSupportKt found in modules jetified-mockk-agent-android-1.12.0-runtime (io.mockk:mockk-agent-android:1.12.0) and jetified-mockk-agent-jvm-1.12.0 (io.mockk:mockk-agent-jvm:1.12.0)
```

#### Minimal reproducible code (the gist of this issue)

```gradle
dependencies {
	...
    testImplementation "io.mockk:mockk:1.12.0"
    testImplementation "io.mockk:mockk-agent-jvm:1.12.0"
	...
	androidTestImplementation "io.mockk:mockk-android:1.12.0"
    androidTestImplementation "io.mockk:mockk-agent-jvm:1.12.0"
}
```

```kotlin
@Test
fun noPermission() {
    ActivityScenario.launch(MainActivity::class.java).use {
        onView(withId(R.id.has_permission))
            .check(matches(withText("No permission.")))
    }
}
```

**Comment by StormPooper** [comment]
@HarisHoulis yep, this workaround works for me too.

**Comment by abbisea** [comment]
Still having this issue on 1.12.3

**Comment by azabost** [comment]
> What **worked** for me was _excluding_ the second module for the `androidTestImplementation` configuration:
> 
> ```groovy
>     configurations {
>         androidTestImplementation {
>             exclude group: 'io.mockk', module: 'mockk-agent-jvm'
>         }
>     }
> ```

Any idea how to apply this to all the modules at once?

When I tried this in the top-level (root) `build.gradle.kts`:

```
allprojects {
    configurations.findByName("androidTestImplementation")?.run {
        logger.log(LogLevel.LIFECYCLE, "Excluding mockk-jvm-agent from: $projectName")
        exclude(group = "io.mockk", module = "mockk-agent-jvm")
    } ?: run {
        logger.log(LogLevel.LIFECYCLE, "Skipping exclusion of mockk-jvm-agent from: $projectName")
    }
}
```

then it didn't work. It looks like at this stage the `configurations` are not prepared yet so there is no way to find `androidTestImplementation`.

The suggested workaround worked for me only when I added it in the module-specific `build.gradle.kts` file but I don't want to add it to all of my modules because it's really tedious and easy to forget about, not to mention updating this in the future if necessary.

Do you really think this issue should be closed already? Is there no way for the `mockk` library to fix this problem?
