### ISSUE TITLE
jvm target issue on 1.11.0

### ISSUE THREAD

**Issue by rlatapy-luna** [mockk/mockk#588]
### Current Behavior

Since mockk 1.11.0, I got several errors pointing to `mockkClass` fun usage when I compile my tests. I did not change anything on my side, it works on 1.10.6.
`Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option`

#### Steps to Reproduce

Run gradle task `compileTest`

#### Context

* MockK version: 1.11.0
* OS: MacOS
* Kotlin version: 1.4.31 (with IR compiler enable)
* JDK version: 1.8
* JUnit version: 1.1.2
* Type of test: unit test

**Comment by Raibaz** [comment]
By default, the kotlin compiler targets JVM 1.6, but since you are using JDK 1.8 you can explicitly target it by doing

```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = "1.8"
    }
 }
```

In your build.gradle.

Let me know if it works.

**Comment by qmetzler-luna** [comment]
Your snippet didn't work but adding the following did the trick
```
compileTestKotlin {
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }
}
```
Thanks for pointing out the right direction 😄

**Comment by rlatapy-luna** [comment]
Thanks, but it still weird that we do not need this with previous versions

**Comment by calvarez-ov** [comment]
Any tips for how to configure this in an android project?

I've added this, but it doesn't help (I get the same compilation errors):
```gradle
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }
```

`compileTestKotlin` doesn't seem to be recognized (I get different errors depending on where I try to place this)
